source 'https://rubygems.org'

#ruby=2.1.1
#ruby-gemset=niball

# Pry
gem 'pry'

# Server requirements
gem 'thin'

# Project requirements
gem 'rake'

# Websockets
gem 'em-websocket'

# Protocol bufffers
gem 'beefcake'
